### ISSUE TITLE
等级完成表的bug（？

### ISSUE THREAD

**Issue by Kincy1151** [xszqxszq/maimai-bot#13]
插件刚启动会缓存若干初始等级封面表
然后代码逻辑会将每次查询等级表后印好用户成绩的表覆盖这张初始的表
导致每查询一次会越来越黑逐渐看不见歌曲封面，也能隐约看到上一个查询用户的成绩（
总之查多几次就用不了了

**Comment by Kincy1151** [comment]
好像上次反馈的时候说过 草 但是这个bug看起来还在（

**Comment by xszqxszq** [comment]
最新版修了啊，可以提供复现条件吗

**Comment by Kincy1151** [comment]
比如反复查询14完成表试试？难道是有什么文件夹需要清理之类的我没有清理



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月8日(周四) 晚上6:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xszqxszq/maimai-bot] 等级完成表的bug（？ (Issue #13)

**Comment by xszqxszq** [comment]
检查一下 plugins 文件夹里面是不是有老版本没删，然后删掉 config/xyz.xszq.maimai-bot 和 data/xyz.xszq.maimai-bot 两个文件夹

**Comment by Kincy1151** [comment]
已经删掉重试了 还是有这个问题
图三是删掉两个文件夹之后控制台缓存完毕之后的输出
图一是第一次查询，图二是第三次查询 图二已经看不清原歌曲封面了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月8日(周四) 晚上6:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xszqxszq/maimai-bot] 等级完成表的bug（？ (Issue #13)




 
检查一下 plugins 文件夹里面是不是有老版本没删，然后删掉 config/xyz.xszq.maimai-bot 和 data/xyz.xszq.maimai-bot 两个文件夹

**Comment by xszqxszq** [comment]
图好像没发上来。我使用了以下版本重新在 Windows 上搭了新的 mirai 运行环境并重启运行多次，并未复现本 bug：
mcl 版本：`2.1.2-61c8bd8`
mirai-console 版本: `2.13.2`
插件文件名：`maimai-bot-1.3.3.mirai.jar`

下载最新版请在 [Release](https://github.com/xszqxszq/maimai-bot/releases/latest) 中下载，README 中的链接确实有误链接到老版本了

**Comment by Kincy1151** [comment]
> 图好像没发上来。我使用了以下版本重新在 Windows 上搭了新的 mirai 运行环境并重启运行多次，并未复现本 bug： mcl 版本：`2.1.2-61c8bd8` mirai-console 版本: `2.13.2` 插件文件名：`maimai-bot-1.3.3.mirai.jar`
> 
> 下载最新版请在 [Release](https://github.com/xszqxszq/maimai-bot/releases/latest) 中下载，README 中的链接确实有误链接到老版本了

 更新后已经修改了，非常感谢！
