### ISSUE TITLE
希望可以有一个命令的帮助

### ISSUE THREAD

**Issue by xixi-furry** [xszqxszq/maimai-bot#16]
感谢大佬的制作，但是希望能够有一个help或者帮助的命令能够输出各项命令具体用什么来触发，还有就是b40和b50这样的，第一次生成比较慢，希望可以有一个正在生成的提示，不然也不知道到底出发没。希望大佬考虑一下~

**Comment by xszqxszq** [comment]
确实，帮助命令要加，不过b40理论上生成不会太慢，我再优化一下吧

**Comment by xixi-furry** [comment]
快慢其实都还好，主要是用户侧不知道触发没，最好是触发了有个正在生成中的提示

帮助命令希望大佬能够加上具体的格式，会方便一点（）今天硬是一个个测得哈哈哈哈

**Comment by xszqxszq** [comment]
生成中的提示现在可以在配置文件中启用了
帮助请使用/mai help
