### ISSUE TITLE
希望添加插件自动重载功能

### ISSUE THREAD

**Issue by whitebearovo** [xszqxszq/maimai-bot#18]
每次版本更新都需要手动重启mirai才能更新插件和别名，希望能加入插件自动重载功能（

**Comment by xszqxszq** [comment]
现在可以使用 `/perm grant u123456 maimaiBot:admin` 设置插件管理员，然后可以使用 `/mai reload` 命令重载图片和别名，或者 `/mai themereload` 仅重载主题。文档后续将会跟进
