### ISSUE TITLE
完成表和定数表生成失败bug

### ISSUE THREAD

**Issue by AKAPotato** [xszqxszq/maimai-bot#19]
完成表和定数表好像又炸了

![photo_2023-05-04_19-13-20](https://user-images.githubusercontent.com/35820942/236813529-ded66d04-2806-4181-876a-51b5588d7357.jpg)

**Comment by xszqxszq** [comment]
如果能复现把Temp/ds文件夹打包发一下

**Comment by AKAPotato** [comment]
> 如果能复现把Temp/ds文件夹打包发一下

没有看到有Temp/ds文件夹，但是有log，已经发到telegram上了，有空的话可以看看（？）

**Comment by xszqxszq** [comment]
现在再试试？

**Comment by AKAPotato** [comment]
> 现在再试试？

已修复，感谢！辛苦了！
