### ISSUE TITLE
2023版本歌曲的别名丢失

### ISSUE THREAD

**Issue by whitebearovo** [xszqxszq/maimai-bot#24]
如图,2023歌曲的别名丢失无法查询，重启后问题依旧
![6b9c61a39e60397c](https://github.com/xszqxszq/maimai-bot/assets/76813756/3abffd36-bd87-4036-831e-5d510ad29ca8)

**Comment by xszqxszq** [comment]
xray的别名api那边跟查分器的id不一样

**Comment by xszqxszq** [comment]
upd 2023.9.23 请在配置文件里将 `xrayAliasUrl` 改成 https://download.fanyu.site/maimai/alias.json
