### ISSUE TITLE
对猜歌功能的一个建议

### ISSUE THREAD

**Issue by MC57348** [xszqxszq/maimai-bot#5]
我群群友今日沉迷猜歌,但是bot会出现重复多次出现同一题的情况,频率非常的高
所以希望可能调整一下猜歌出题的频率或者检测出题次数过多的歌暂时不能出题?

**Comment by xszqxszq** [comment]
👌

**Comment by xszqxszq** [comment]
试试新版，现在是随机不重复选歌了
