### ISSUE TITLE
关于一些bug

### ISSUE THREAD

**Issue by Kincy1151** [xszqxszq/maimai-bot#6]
b50调用的歌曲rating还是b40的：
需要用getNewRa()之后再重新排序一下
将牌无法正常生成：
这个应该是queryPlateRecord()调用目录的问题，修改下就能正常生成
橙将和晓将完成表无法正常生成：
都是歌曲封面没有被正常缓存的原因，橙将是因为一首11+叫Link的歌跟maimai plus里面一首也叫Link的歌冲突了，导致插件以为已经有该封面所以没有缓存；
晓将是因为13+的一首D✪N’T ST✪P R✪CKIN’ 的歌，猜测是字符串解析有问题，无法被正常缓存；
把封面手动添加到data里面再修改相应id就可以正常生成。
超系牌完成表生成两次：
list里面写多了一个“超”

**Comment by xszqxszq** [comment]
感谢感谢，马上修

**Comment by Kincy1151** [comment]
生成等级完成表的时候使用的不是预先缓存的来着，但是代码里好像不是克隆预先缓存图片，导致每次生成的时候都是覆盖上一次生成的表orz，举个例子群友A查了个14完成表，下一次再有人查的时候会在已经印上群友A的成绩的完成表上继续印成绩，不仅曲绘越来越黑成绩也乱七八糟的（）



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月25日(周二) 上午8:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xszqxszq/maimai-bot] 关于一些bug (Issue #6)




 
感谢感谢，马上修

**Comment by xszqxszq** [comment]
修好了，试试新版

**Comment by Kincy1151** [comment]
辛苦辛苦，都解决了（之前晓将那个bug的原因还找了好久hhh）
