### ISSUE TITLE
不要直接使用 GlobalEventChannel

### ISSUE THREAD

**Issue by cssxsh** [xszqxszq/maimai-bot#8]
直接从 `GlobalEventChannel` 得到的监听器不受 插件生命周期管理

https://github.com/xszqxszq/maimai-bot/blob/0ca5fb3fa87d02df4053a1935b6a2f13ebefb5e0/src/main/kotlin/MaimaiBot.kt#L94

你应该使用 `CoroutineScope.globalEventChannel()` 这个扩展方法, 
`KotlinPlugin/JvmPlugin` 就是 `CoroutineScope` 的子类实现

所以你可以 直接使用 `var channel: EventChannel<Event> = globalEventChannel()` 替换原本的代码

**Comment by xszqxszq** [comment]
👌
