### ISSUE TITLE
对随机推分功能的一个建议

### ISSUE THREAD

**Issue by MC57348** [xszqxszq/maimai-bot#9]
今天群友在roll推分的时候跟我抱怨说一个一个roll太麻烦了，而且随机出来的歌的难度范围有点难以预测。
所以在想能不能加一个随机推分列表的功能
或者是指定某一个等级难度进行列表的抽取

**Comment by xszqxszq** [comment]
写好了

**Comment by MC57348** [comment]
> 写好了

您您您您您您您您您您您您您您您您您您您您
